---

- hosts: localhost
  tasks:
    - name: copy udev mount rules
      copy: src=../udev/50-vagrant-mount.rules dest=/etc/udev/rules.d/50-vagrant-mount.rules

    - name: software - copy config files
      copy: src=../config/{{ item.file }} dest={{ item.path }}
      with_items:
        - { file: 'elasticsearch.yml', path: '/usr/local/elasticsearch/config/elasticsearch.yml' }
        - { file: 'mongodb.conf', path: '/etc/mongod.conf' }
        - { file: 'mysql.conf', path: '/etc/mysql/my.cnf' }
        - { file: 'redis.conf', path: '/etc/redis.conf' }
        - { file: 'nginx.conf', path: '/usr/local/nginx/conf/nginx.conf' }
        - { file: 'php.ini', path: '/usr/local/lib/php.ini' }
        - { file: 'php-fpm.conf', path: '/usr/local/etc/php-fpm.conf' }
        - { file: 'hhvm-php.ini', path: '/etc/hhvm/php.ini' }
        - { file: 'hhvm-server.ini', path: '/etc/hhvm/server.ini' }
        - { file: 'kafka-server.properties', path: '/usr/local/kafka/config/server.properties'}
        - { file: 'kafka-zookeeper.properties', path: '/usr/local/kafka/config/zookeeper.properties' }
      ignore_errors: True

    - name: software - copy custom config files
      copy: src=../../.config/{{ item.file }} dest={{ item.path }}
      with_items:
        - { file: 'elasticsearch.yml', path: '/usr/local/elasticsearch/config/elasticsearch.yml' }
        - { file: 'mongodb.conf', path: '/etc/mongod.conf' }
        - { file: 'mysql.conf', path: '/etc/mysql/my.cnf' }
        - { file: 'redis.conf', path: '/etc/redis.conf' }
        - { file: 'nginx.conf', path: '/usr/local/nginx/conf/nginx.conf' }
        - { file: 'php.ini', path: '/usr/local/lib/php.ini' }
        - { file: 'php-fpm.conf', path: '/usr/local/etc/php-fpm.conf' }
        - { file: 'hhvm-php.ini', path: '/etc/hhvm/php.ini' }
        - { file: 'hhvm-server.ini', path: '/etc/hhvm/server.ini' }
        - { file: 'kafka-server.properties', path: '/usr/local/kafka/config/server.properties'}
        - { file: 'kafka-zookeeper.properties', path: '/usr/local/kafka/config/zookeeper.properties' }
      ignore_errors: True

    - name: software - copy custom .zshrc
      copy: src=../../.config/.zshrc owner={{ item.owner }} group={{ item.owner }} dest={{ item.path }}/.zshrc
      with_items:
        - { owner: 'root', path: '/root' }
        - { owner: 'vagrant', path: '/home/vagrant' }
      ignore_errors: True

    - name: systemd - copy service files
      copy: src=../services/{{ item }} dest=/etc/systemd/system/{{ item }}
      with_items:
        - elasticsearch.service
        - nginx.service
        - php-fpm.service
        - redis.service
        - zookeeper.service
        - kafka.service

    - name: systemd - reload service units
      command: /bin/systemctl --system daemon-reload

    - name: systemd - enable services
      command: /bin/systemctl enable {{ item }}
      with_items:
        - elasticsearch.service
        - mongod.service
        - mysql.service
        - nginx.service
        - php-fpm.service
        - redis.service
        - zookeeper.service
        - kafka.service

    - name: systemd - restart services
      command: /bin/systemctl restart {{ item }}
      with_items:
        - elasticsearch.service
        - mongod.service
        - mysql.service
        - nginx.service
        - hhvm.service
        - php-fpm.service
        - redis.service
        - zookeeper.service
        - kafka.service
      ignore_errors: True
