---

- hosts: localhost
  vars_files:
    - ../ansible-playbooks/vars/software.yml
  roles:
    - { role: ../ansible-playbooks/roles/common, tags: ['default'] }

    - { role: ../ansible-playbooks/roles/imagemagick, tags: ['imagemagick', 'vips'] }
    - { role: ../ansible-playbooks/roles/ffmpeg, tags: ['ffmpeg'] }
    - { role: ../ansible-playbooks/roles/mozjpeg, tags: ['mozjpeg'] }
    - { role: ../ansible-playbooks/roles/vips, tags: ['vips'] }
    - { role: ../ansible-playbooks/roles/zopfli, tags: ['zopfli'] }

    - { role: ../ansible-playbooks/roles/geoip, tags: ['bind', 'geoip'] }
    - { role: ../ansible-playbooks/roles/bind, tags: ['bind'] }
    - { role: ../ansible-playbooks/roles/nginx, tags: ['nginx'] }

    - { role: ../ansible-playbooks/roles/cassandra, tags: ['cassandra'] }
    - { role: ../ansible-playbooks/roles/mysql, tags: ['mysql'] }
    - { role: ../ansible-playbooks/roles/redis, tags: ['redis'] }
    - { role: ../ansible-playbooks/roles/postgres, tags: ['postgres'] }

    - { role: ../ansible-playbooks/roles/elasticsearch, tags: ['elasticsearch'] }
    - { role: ../ansible-playbooks/roles/sphinxsearch, tags: ['sphinxsearch'] }

    - { role: ../ansible-playbooks/roles/kafka, tags: ['kafka'] }

    - { role: ../ansible-playbooks/roles/iojs, tags: ['iojs'] }
    - { role: ../ansible-playbooks/roles/php, tags: ['php'] }
    - { role: ../ansible-playbooks/roles/hhvm, tags: ['hhvm'] }

- hosts: localhost
  tasks:
    - name: install extra software
      apt: pkg={{ item }} state=installed
      with_items:
        - advancecomp
        - jpegoptim
        - openjdk-7-jdk
        - optipng
        - pngcrush
        - vim
        - zsh

    - name: change default shell for root and vagrant users
      user: name={{ item }} shell=/bin/zsh
      with_items:
        - root
        - vagrant

    - name: copy base .zshrc
      copy: src=../config/.zshrc owner={{ item.owner }} group={{ item.owner }} dest={{ item.path }}/.zshrc
      with_items:
        - { owner: 'root', path: '/root' }
        - { owner: 'vagrant', path: '/home/vagrant' }

    - name: install tmuxinator
      gem: name=tmuxinator state=latest

    - name: create default vagrant user for postgres
      postgresql_user: name=vagrant password=vagrant role_attr_flags=CREATEDB,SUPERUSER
